apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: introspect-1b-cluster
  region: us-east-1
  version: "1.34"
  tags:
    karpenter.sh/discovery: introspect-1b-cluster

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cluster-admin
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AdministratorAccess

managedNodeGroups:
  - name: mng-od-4vcpu-4gb
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    instanceType: t3.medium
    privateNetworking: true

addons:
  - name: vpc-cni 
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest 
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    wellKnownPolicies: 
      ebsCSIController: true
