apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: introspect-1b-cluster-2
  region: us-east-1
  version: "1.34"
  tags:
    karpenter.sh/discovery: introspect-1b-cluster-2

managedNodeGroups:
  - name: mng-od-2vcpu-2gb
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    instanceType: t3.small
    privateNetworking: true

addons:
  - name: vpc-cni 
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest 
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    wellKnownPolicies: 
      ebsCSIController: true
