apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-subscription
spec:
  pubsubname: product-pubsub
  topic: product.new
  routes:
    default: /orders/handle
  scopes:
  - order-service